### ISSUE TITLE
Crash during config loading

### ISSUE THREAD

**Issue by Zemogiter** [LXGaming/MixinBootstrap#16]
MC version: 1.15.2
Forge version: 31.1.75
Crash log:
[2020-05-06-6.log](https://github.com/LXGaming/MixinBootstrap/files/4588838/2020-05-06-6.log)
Happens in "FML early loading" stage.

**Comment by LXGaming** [comment]
Please provide the `debug.log` file as well as the list of mods you have present so we can track down the mod which owns `tpsgenerator.mixins.json`

**Comment by Zemogiter** [comment]
[debug.log](https://github.com/LXGaming/MixinBootstrap/files/4589074/debug.log)
[modlist.txt](https://github.com/LXGaming/MixinBootstrap/files/4589136/modlist.txt)

**Comment by LXGaming** [comment]
Remove `tpsgenerator-1.0.jar`, The mods manifest contains a MixinConfigs entry but there doesn't appear to be any Mixin related stuff in the mod. The entry was probably added during development but then never removed.

@Tfarcenim - mentioning the developer here as this mod doesn't have an issue tracker on CurseForge or GitHub.

**Comment by Zemogiter** [comment]
Removing that mod solved the problem. I've informed the developer at CurseForge.

**Comment by DrUltraLux** [comment]
I am having the exact same issue but with only the latest Forge, Mixin and Optifine (15.2) and nothing  else running. 

It crashes without generating any log files even. 

Disabling MixinBoostrap completely solves the problem.

**Comment by DrUltraLux** [comment]
I tried a fresh minecraft with nothing but MixinBootstrap and the current forge. No dice.

**Comment by LXGaming** [comment]
Please provided the `debug.log` file

**Comment by DrUltraLux** [comment]
There was no debug.log. I can't see any such file  anywhere anyway.

However I solved it. 
If I manually install forge in .minecraft and run it with mixin it works  fine. 

The issue only occurs when I setup a modpack in twitch.
I was able to copy the complete profile into a twitch directory and load it in twitch and it runs fine now.
