### ISSUE TITLE
crash when starting up

### ISSUE THREAD

**Issue by zorkmork** [LXGaming/MixinBootstrap#18]
im not that good with mods, but it seems something is wrong with the mixin bootstraps im using, and idk what to do. it immediately crashes..... 

[crash-2020-06-05_17.21.49-client.txt](https://github.com/LXGaming/MixinBootstrap/files/4738576/crash-2020-06-05_17.21.49-client.txt)
heres the crash report

**Comment by LXGaming** [comment]
Looks like an issue with OptiForge, Try downgrading OptiFine to pre20, It could be that OptiForge doesn't support pre21 yet

**Comment by zorkmork** [comment]
Optifine only has the option to download pre21, where can I find the pre20
version?

**Comment by LXGaming** [comment]
https://optifine.net/adloadx?f=preview_OptiFine_1.15.2_HD_U_G1_pre20.jar

**Comment by zorkmork** [comment]
when i go to download it, it says "file not found"

**Comment by LXGaming** [comment]
Ah sorry, I didn't test it that far, I assumed that page showing up indicated that the file existed. You're going to have to wait for OptiForge to add support for pre21

**Comment by zorkmork** [comment]
oki doki
