### ISSUE TITLE
Crash upon startup of Minecraft (1.15.2)

### ISSUE THREAD

**Issue by DatrixTHLK** [LXGaming/MixinBootstrap#2]
Hi,

I'm getting an error when I installed this mixin to the mods folder and playing Minecraft 1.15.2 Not sure what went wrong. I was told to install mixin by betterbedrockgen and dankstorage. Once I did all I keep getting is a critical error when initiallizing game. 

Minecraft: 1.15.2
Forge: 31.0.1
BBG: 0.0.3
Dank Storage: 2.4b
MixinBootstrap: 1.0.1

I feel like I'm missing something or a mod that is needed that I don't have.

**Comment by LXGaming** [comment]
Fixed in Better Bedrock Generator v0.0.4
