### ISSUE TITLE
Question about supported forge versions [1.12.2]

### ISSUE THREAD

**Issue by BunnyCinnamon** [LXGaming/MixinBootstrap#21]
Hello, I'm so sorry for creating an issue for this, but I don't know anyone that can help, I really tried to figure out on my own what my error is but I just don't know what to do, and so here is the question:

- Do I need a specific setup to load MixinBootstrap with forge 1.12.2?

I could not find any 1.12.2 examples so I followed what 1.15.2 projects have, I attempted using the same gradle script as this other project: [FruitTrees](https://github.com/Snownee/FruitTrees/blob/master/build.gradle), _but the MixinConnector doesn't load_. I am very new to mixins so please forgive me if I'm not following the obvious steps.
This is my git repo: [BetterHurtTimer](https://github.com/ArekkuusuJerii/BetterHurtTimer)
Thank you :>

**Comment by LXGaming** [comment]
Add `"TweakClass": "org.spongepowered.asm.launch.MixinTweaker"` to the manifest attributes in your build.gradle, This should fix it so your MixinConnector gets loaded.

**Comment by BunnyCinnamon** [comment]
Oh my god that worked! Thank you so much :0

**Comment by LXGaming** [comment]
No problem, If you have any additional questions you can comment on this issue.
