### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by Kasyader** [LXGaming/MixinBootstrap#22]
Game is just crashing

One function of Bootstrap crashed the game (I think lol)

[15cze2020 08:52:59.882] [Client thread/INFO] [STDOUT/]: [net.minecraft.util.registry.Bootstrap:func_179870_a:100]: #@!@# Game crashed! 

If you need more text from **latest.log or debug.log** please  message

**Comment by LXGaming** [comment]
Please provide the `debug.log`, If it doesn't exist then the `latest.log`.

**Comment by Kasyader** [comment]
[debug.log](https://github.com/LXGaming/MixinBootstrap/files/4778523/debug.log)

**Comment by LXGaming** [comment]
Looks like an incompatibility between OptiFine and BetterFoliage.

**Comment by Kasyader** [comment]
But if I turn on Minecraft with Optifine and Better Foliage (Without Bootstrap) it works...
But Better Floiage doesn't work when I load any world.

**Comment by LXGaming** [comment]
That's because MixinBootstrap is a library mod which is used by BetterFoliage, If you remove MixinBootstrap then BetterFoliage won't work.

You're best option would be to remove BetterFoliage as it's known to breaks other mods (https://github.com/LXGaming/MixinBootstrap/issues/9)

**Comment by Kasyader** [comment]
Okay, thank you, but where can I download working version of Better Foliage??

**Comment by LXGaming** [comment]
There is no working version available, the last update was 6 months ago.

**Comment by Kasyader** [comment]
So I need to wait...

Okay, Thank You and good day :)
