### ISSUE TITLE
Minecraft crashes

### ISSUE THREAD

**Issue by javiermisol** [LXGaming/MixinBootstrap#24]
If I start Minecraft with this mod, Minecraft crashes.

12:18:37.978
[m[32m[12:18:37] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector redirect$render$2(Lnet/minecraft/client/gui/screen/MainMenuScreen;Ljava/lang/String;)V in mixins.optiforge.json:net.minecraft.client.gui.screen.MixinMainMenuScreen failed injection check, (0/1) succeeded. Scanned 1 target(s). No refMap loaded.
12:18:37.978
[m[32m[12:18:37] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:400)
12:18:37.978
[m[32m[12:18:37] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: 	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1280)
12:18:37.979
[m[32m[12:18:37] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042)
12:18:37.979
[m[32m[12:18:37] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
12:18:37.979
[m[32m[12:18:37] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
12:18:37.979
[m[32m[12:18:37] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
12:18:37.979
[m[32m[12:18:37] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:570)
12:18:37.979
[m[32m[12:18:37] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
12:18:37.979
[m[32m[12:18:37] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: 	... 24 more
12:18:38.394
[m
12:18:38.394
Process crashed with exit code 1

**Comment by LXGaming** [comment]
Please provide `debug.log` file.

Looking at what you posted `mixins.optiforge.json` indicates that the issue is most likely an incompatibility between OptiFine and OptiForge.

**Comment by javiermisol** [comment]
ok if that is so, I will go to a previous version, since I see that it works for the moment, and I will give notice to the development of optiforge.
Thanks for clarification.
