### ISSUE TITLE
Game Crashes When Loading World

### ISSUE THREAD

**Issue by Suhooby** [LXGaming/MixinBootstrap#25]
**Environment**
- MixinBootstrap version:1.0.3
- Forge version:31.2.0
- Minecraft version:1.15.2
- Java version:
- Mods:Xaeros Minimap, jei, RPG HUD, Bioms-o-plenty, ores-above-diamond,optiforge,optifine preview 30. 

**Issue Description**
 game crashes when i try to open my world.

[debug.log](https://github.com/LXGaming/MixinBootstrap/files/4815612/debug.log)

**Comment by LXGaming** [comment]
Looks like an issue with OptiForge.

Looking at [OptiForge on CurseForge](https://www.curseforge.com/minecraft/mc-mods/optiforge) it states that OptiFine pre30 requires OptiForge v0.1.26 and Forge v31.2.15. So update those mods and see if it fixes the issue.

**Comment by Suhooby** [comment]
Thank you it worked!
