### ISSUE TITLE
Minecraft crashing

### ISSUE THREAD

**Issue by daisy323** [LXGaming/MixinBootstrap#27]
[crash-2020-07-05_02.31.59-server.txt](https://github.com/LXGaming/MixinBootstrap/files/4874519/crash-2020-07-05_02.31.59-server.txt)
**Environment**
- MixinBootstrap version: 1.15.2
- Forge version: 1.15.2 - 31.2.9
- Minecraft version: 1.15.2
- Java version: java 8
- Mods: biomesoplenty, dragon mounts,kiwibirds,jei, quark,journeymap,mrclayfish furniture,xaeros minimap,skye'sbakery,bonsaitrees,productive bees,pandoras creatures,aquaculture,druidcraft,improved wolves,venture,sleepingdogs,autoreglib,libnonymous,

**Issue Description**
 Minecraft crashes when click on start playing world.

[crash-2020-07-05_02.31.59-server.txt](https://github.com/LXGaming/MixinBootstrap/files/4874524/crash-2020-07-05_02.31.59-server.txt)

**Comment by LXGaming** [comment]
Looks like an issue with OptiForge.

Looking at [OptiForge on CurseForge](https://www.curseforge.com/minecraft/mc-mods/optiforge) it states that OptiFine pre30 requires OptiForge v0.1.27 and Forge v31.2.23. So update those mods and see if it fixes the issue.
