### ISSUE TITLE
Minecraft crashing when launching

### ISSUE THREAD

**Issue by AnErrupTion** [LXGaming/MixinBootstrap#28]
**Environment**
- MixinBootstrap version: 1.0.3
- Forge version: 31.2.23
- Minecraft version: 1.15.2
- Java version: OpenJDK 11
- Mods: Camera Mod, Creative Core, Enhanced Visuals, First Aid, Immersive Portals, Just A Raft Mod, MixinBootstrap, OptiForge, Pam's HarvestCraft 2, OptiFine pre30, Realistic Torches, SimplyTea, ToolBelt, WorleyCaves.

**Issue Description**

When I launch Minecraft, after finishing the deep scan of the mods, it crashes. Only occurs when OptiFine pre30 is installed.

[latest.log](https://github.com/LXGaming/MixinBootstrap/files/4874907/latest.log)
[debug.log](https://github.com/LXGaming/MixinBootstrap/files/4874908/debug.log)

**Comment by LXGaming** [comment]
Looks like an issue with Immersive Portals and OptiFine.

Please update Immersive Portals as it does appear the developer did fix this specific issue: https://github.com/qouteall/ImmersivePortalsModForForge/commit/3d67ed88a316a89823a49ed9aea81fa3b28f4a88#diff-0bd37bf5bc4587c1b6a0e5a1e742b0f4
