### ISSUE TITLE
[1.16.1] Crash on world creation

### ISSUE THREAD

**Issue by NielsPilgaard** [LXGaming/MixinBootstrap#29]
**Environment**
- MixinBootstrap version: MixinBootstrap-1.0.3
- Forge version: 1.16.1-32.0.47
- Minecraft version: 1.16.1
- Java version: Latest Java 8 (250 something)
- Mods: Modpack Enigmatica 6 development build: https://gist.github.com/NillerMedDild/eb2ca7cb6e4d0bf5e01fbc9face72533

**Issue Description**

Instant crash when creating a new world.

Latest: https://gist.github.com/NillerMedDild/d7c59c28f141985fddae44ef2f2040f7
Debug: https://gist.github.com/NillerMedDild/42a577c43cd69f3df81cd86286c99b43

**Comment by LXGaming** [comment]
Looks like an issue with KubeJS.

Related issue: https://github.com/KubeJS-Mods/KubeJS/issues/15
