### ISSUE TITLE
crash to launcher 1.14.4

### ISSUE THREAD

**Issue by VarianArdell** [LXGaming/MixinBootstrap#3]
as of today, I am currently unable to launch my modloader with Immersive Portals and Better Bedrock Generator (among other mods), both of which require MixinBootstrap. was able to recreate the modpack without those mods and the bootstrap, and it launches fine, but as soon as I add either one of those mods and the bootstrap, it gives the following message: "ERROR Game Crashed An unexpected issue occurred and the game has crashed. We're sorry for the inconvenience."

running on forge version 28.1.117; additional information can be provided upon request

**Comment by LXGaming** [comment]
Can you provide the debug.log? And provided a list of mods with the version you are running.

**Comment by VarianArdell** [comment]
> Can you provide the debug.log? And provided a list of mods with the version you are running.

where do I find the debug.log? and [here's](https://pastebin.com/hK8XDPkh) the mod list

**Comment by VarianArdell** [comment]
for what it's worth though, I just set up a test profile on Twitch with just Immersive Portals and Better Bedrock Generator, and I'm getting the same error

**Comment by LXGaming** [comment]
Same issue: https://github.com/nevoka-be/BetterBedrockGenerator/issues/2
The developer didn't backport the fix to 1.14.4

**Comment by VarianArdell** [comment]
> Same issue: [nevoka-be/BetterBedrockGenerator#2](https://github.com/nevoka-be/BetterBedrockGenerator/issues/2)
> The developer didn't backport the fix to 1.14.4

that wouldn't explain why it was working until yesterday, but not today... literally nothing changed

**Comment by LXGaming** [comment]
Interesting, The fix is present in BBG v1.14.4-0.0.4 but not in BBG v1.14.4-0.0.5

**Comment by VarianArdell** [comment]
alright, can confirm the issue does seem to have been fixed by reverting to BBG v1.14.4-0.0.4, which apparently I updated but do not recall doing so...

**Comment by LXGaming** [comment]
This issue has been fixed in BBG v1.14.4-0.0.6
