### ISSUE TITLE
Client crash: mouseClicked event handler

### ISSUE THREAD

**Issue by ClaudiusMinimus** [LXGaming/MixinBootstrap#30]
Client crashed when trying to load world

Minecraft: 1.16.1
Forge: 32.0.59
MixinBootstrap 1.0.3

https://paste.ee/p/euGzk

Mods:
- [1.16.1]-additionalbars-1.3.6
- AdditionalEnchantedMiner-1.16.1-16.0.3
- angelring-1.16.1-1.3.0
- Animalium-0.6.0
- bambooeverything-1.16-1.0.0
- Better+Muffling-1.16.1-0.5.0-Beta
- Bettersigns-1.0_v1.16.1
- BioTechnik-1.16.1-1.0.0
- borderless-1.16.1-1.1.0
- branders-spawnermod-1.16.1-1.6.5
- branders-wellfedmod-1.16.1-1.3.1
- BridgeMaker-1.16.1-1.0.0
- bspawncontrol_1.16-1.1
- citadel-1.2.0
- Clay+WorldGen-1.1.0-1.16.1
- cleancut-mc1.16.1-2.1-forge
- ClientTweaks_1.16.1-5.0.0
- cloth-config-forge-4.0.1
- collective-1.16.1-1.35
- CookingForBlockheads_1.16.1-9.0.0
- CosmeticArmorReworked-1.16.1-v1
- CraftingCraft_1.16.1-9.0.0
- CraftingTweaks_1.16.1-12.0.3
- CTM-MC1.16.1-1.1.0.1
- curioofundying-FORGE-1.16.1-4.0
- curios-FORGE-1.16.1-3.0-beta2
- curiousshulkerboxes-FORGE-1.16.1-3.0
- dash-1.16.1-1.0.1
- decorative_blocks-1.16-0.2
- DefaultOptions_1.16.1-12.0.0
- doubledoors_1.16-2.1
- DoubleSlabs-1.16-3.0.1
- dungeons-plus-1.16.1-1.0.2
- dwarfcoal-1.16.1-1.0
- EasierSleeping-1.16.1-1.0.0
- elevatorid-1.16.1-1.7.2
- EnderRift-1.16.1-2.2.6
- engineerstools-1.16.1-1.0.8-a1
- entangled-1.2.5-mc1.16
- factory-1.16.1-1.0.1
- farlanders-1.16.1-1.3.2
- FarmingForBlockheads_1.16.1-7.0.0
- FastLeafDecay-v23
- gates-1.6.1
- giantspawn_1.16-2.1
- globalxp-1.16.1-v1.4.12
- gravestone-1.16.1-1.0.2
- grindstonesharpertools_1.16-1.4
- guardvillagers-1.16.1-1.1.0
- Guidebook-1.16.1-3.1.1
- improved-stations-2.0
- Industrial-Reborn-1.16.1-0.7.0
- InventoryEssentials_1.16.1-2.0.0
- invisiblights-forge-6.0
- invtweaks-1.16.1-1.0.2
- ironfurnaces-1.16.1-2.1.1
- ironshulkerboxes-1.16.1-5.0.1
- jei-1.16.1-7.0.0.3
- JEIEnchantmentInfo-1.16.1-1.1.0
- justmobheads_1.16-3.4
- justplayerheads_1.16-1.1
- kelpfertilizer_1.16-1.1
- kubejs-2.7.0.42
- LargeFluidTank-16.0.1
- leap-1.16.1-1.0.1
- light-overlay-5.4.0
- lightestlamp-4.0.2
- mahoutsukai-1.16.1-v1.19.9
- mcw-bridges-1.0.4-mc1.16.1
- mcw-doors-1.0.0-mc1.16.1
- metalbarrels-3.1a
- mining-helmet-1.16.1-1.0.8
- MixinBootstrap-1.0.3
- modnametooltip_1.16.1-1.14.0
- MoreThanAPickaxe-1.16.1-0.1.3
- morevanillalib-1.16.1-1.2.6
- morezombiev_1.16-1.1
- MouseTweaks-2.13-mc1.16.1
- NetherPortalFix_1.16.1-7.0.0
- Overloaded+Compressed+Blocks-1.16.1-1.0.13
- packedup-1.0.15-mc1.16
- PackingTape-1.16.1-0.9.6
- pamhc2foodcore-1.16.1-1.0.0
- Patchouli-1.16-38
- playerplates-1.16.1-forge-1.0.0
- potionsmaster-0.1.7-1.16.1-32.0.57
- QuantumStorage-1.16.1-5.2.0
- rad-1.16-4.0.1
- randomite-1.16.1-1.0.0
- randomloot-2.0.3
- randompatches-1.16.1-1.21.2.1
- rats-6.0.2-1.16.1
- reap-1.16.1-1.0.1
- RedstoneExtras-1.16.1-1.0.0.3
- Regrowth-1.16.1-1.0.0.0
- ResourcefulTools-1.16.1-1.2.0
- RingOfAttraction-1.16.1-1.2.0
- RingOfMiner-1.16.1-1.2.0
- RingOfRepair-1.16.1-1.2.0
- rsgauges-1.16.1-1.2.4-b1
- ScalableCatsForce-2.13.2-build-2-with-library
- Server_Utils-1.16.1-1.3.15
- silencemobs_1.16-1.5
- SimpleDivingGear-5.0.0+mc+1.16.1
- simplegrinder-16.0.5
- SimpleOres2-1.16.1-2.2.0.0
- sleeping_bags-1.16.1-1.0.0
- Stairway_1.16.1_v15
- step-1.16.1-1.0.2
- StorageDrawers-1.16.1-8.0.0
- structure-gel-api-1.16.1-1.1.1
- structurize-0.13.7-ALPHA
- SuperTools-1.0_1.16.1
- SurvivalPlus-1.16.1-0.1.3
- tesseract-1.0.6-mc1.16
- theoneprobe-1.16-3.0.0-beta
- TheVeggieWay-1.16.1-2.2.0
- ToolBelt-1.16.1-1.14.1
- tramplestopper-1.15.2-2.0.0.1-universal
- TrashSlot_1.16.1-12.0.0
- travellersboots-1.16.1-1.4.0
- Uppers-0.3.0
- vanillaexcavators-1.16.1-2.1.1
- vanillahammers-1.16.1-2.1.1
- villagernames_1.16-2.4
- Waystones_1.16.1-7.0.0
- Xaeros_Minimap_20.15.3_Forge_1.16.1
- XaerosWorldMap_1.7.3_Forge_1.16.1

**Comment by LXGaming** [comment]
Looks like an issue with KubeJS.

Related issue: https://github.com/KubeJS-Mods/KubeJS/issues/15

**Comment by LXGaming** [comment]
Fixed in kubejs-2.7.0.43
