### ISSUE TITLE
Crashes on use. No reports are given.

### ISSUE THREAD

**Issue by MagmaSlime123** [LXGaming/MixinBootstrap#34]
**Environment**
- MixinBootstrap version: 1.0.3.
- Forge version: 2854.
- Minecraft version: 1.12.2.
- Java version:
![image](https://user-images.githubusercontent.com/51277766/92331719-8d1e7700-f02d-11ea-9e79-6622ea7faa4a.png)
- Mods: Tested on a fresh install with only this, same issue.

**Issue Description**
Read the title.

[latest.log](https://github.com/LXGaming/MixinBootstrap/files/5180032/latest.log)

**Comment by LXGaming** [comment]
Looks like several other mods are loading Mixin which is causing a conflict with MixinBootstrap, Removing MixinBootstrap should fix the issue.

**Comment by MagmaSlime123** [comment]
A mod requires this to be used with it.

**Comment by LXGaming** [comment]
That mod should still function fine as another mod is providing the Mixin Library.

**Comment by MagmaSlime123** [comment]
Well, this mod crashes with no reports being given. So even without that, same thing happens. Crash with no report.

**Comment by LXGaming** [comment]
Can you upload you're debug.log file, That will contain the crash information.

**Comment by LXGaming** [comment]
Closing due to no response.

The solution to this issue is to remove MixinBootstrap as Mixin is being loaded by several others mods.
