### ISSUE TITLE
Minecraft Crash

### ISSUE THREAD

**Issue by mms7dvs** [LXGaming/MixinBootstrap#36]
**Environment**
- MixinBootstrap version: 1.0.3
- Forge version: I am using the Forge 1.15.2 from Tlauncher
- Minecraft version: 1.15.2

**Issue Description**
When I start the Game it crashes. When I remove the MixinBootstrap it works like always, but I am not sure if it is MixinBootstrap error or maybe Lithium. I don't know if another mod could be crashing my game.
I was using Forge 31.2.20 before, but now I want to use the Forge 1.15.2 because I need this version to create a server with my friends on tlauncher.

[debug.log](https://github.com/LXGaming/MixinBootstrap/files/5270062/debug.log)
[latest.log](https://github.com/LXGaming/MixinBootstrap/files/5270063/latest.log)

**Comment by LXGaming** [comment]
Update OptiForge, You may also have to update Forge. Check the [OptiForge CurseForge](https://www.curseforge.com/minecraft/mc-mods/optiforge) page for which versions you need.
