### ISSUE TITLE
Ubuntu Server Crash: "Service failed to load mixinbootstrap"

### ISSUE THREAD

**Issue by Partonetrain** [LXGaming/MixinBootstrap#4]
Might be a Modlauncher issue rather than a MixinBootstrap issue, but server runs without MixinBootstrap. 

Log with just Forge 31.1.1 and MixinBootstrap:
https://pastebin.com/3hgejMR9

**Comment by LXGaming** [comment]
It's an incompatibility with Java 11, Try using Java 8 if you can.

I will look into this and see if adding Java 11 support is possible.

**Comment by LXGaming** [comment]
[MixinBootstrap v1.0.2](https://github.com/LXGaming/MixinBootstrap/releases/tag/v1.0.2) adds support for Java 11.
