### ISSUE TITLE
Mixin seems to be the cause of a crash

### ISSUE THREAD

**Issue by grandogarndo** [LXGaming/MixinBootstrap#40]
**Environment**
- MixinBootstrap version:1.0.2
- Forge version: 31.2.43
- Minecraft version:1.15.2
- Java version: i always keep it up to date
- Mods: a large amount, will be in the crash log

**Issue Description**
The game crashes and seems to mention mixin, when removed it just crashes quicker, i tried to get help here: https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/mod-packs/3038919-minecraft-keeps-crashing-no-matter-what-mods-i but it ended in a wild goose chase

Crash: https://pastebin.com/eX04PTDr

[latest.log](https://github.com/LXGaming/MixinBootstrap/files/5431958/latest.log)

**Comment by LXGaming** [comment]
Please upload your debug.log file (If it's too large to upload try compressing it)

**Comment by grandogarndo** [comment]
where is that located?

**Comment by LXGaming** [comment]
In the logs folder, It should be in the same folder as your latest.log file.

**Comment by grandogarndo** [comment]
no, its not there.
![Capture](https://user-images.githubusercontent.com/56941237/97061641-8314f100-1565-11eb-8df9-e2a2836d8d72.PNG)

**Comment by LXGaming** [comment]
debug.log not generating is weird.

Looking at latest.log the first error encountered is about a missing class `net.minecraftforge.client.model.ModelLoader$VanillaModelWrapper` given that the rest of the log is filled with what appears to be errors relating to rendering I'm going to guess that there is a mod install which is breaking that class.

Without the debug.log I cannot track the class loading to find which mod is breaking things, And given that the MinecraftForum posts indicate this is a custom pack I assume it's not publicly downloadable which means I cannot debug the pack myself.

I suggest try a different Launcher (I'm assuming the current Launcher you are using is preventing the debug.log from being created), Your going to have to remove each mod until the issue disappears.

**Comment by grandogarndo** [comment]
what launchers are there? i'm using atlauncher currently

**Comment by grandogarndo** [comment]
ok i'm using multimc, atlauncher may be the problem

**Comment by grandogarndo** [comment]
[debug.log](https://github.com/LXGaming/MixinBootstrap/files/5432246/debug.log)
here you go, multimc seemed to use much less ram, but still crashed in the same way.

**Comment by LXGaming** [comment]
I downloaded the mods that were being loaded by Mixin according to the debug.log (additionalevents, dankstorage, pmmo, fruittrees and phosphor) and my client loaded fine. This doesn't appear to be direct Mixin issue and I can't see what the issue might be from the logs.

Given the amount of mods there is probably compatibility issues between one or more of them and the only way to figure that out is to start removing mods.

**Comment by grandogarndo** [comment]
Thanks so much, I just looked at my most recent downloads and removed them, and it worked. I'll close the issue now.
