### ISSUE TITLE
mixinbootstrap causes all the mods 3 to crash

### ISSUE THREAD

**Issue by pirateninjaboi** [LXGaming/MixinBootstrap#41]
**Environment**
- MixinBootstrap version:1.0.5
- Forge version:14.23.5.2854
- Minecraft version:1.12.2
- Java version:lates
- Mods: a lot, modpack; all the mods 3

**Issue Description**
on startup the game instantly crashes

[2021-01-24-1.log.gz](https://github.com/LXGaming/MixinBootstrap/files/5863739/2021-01-24-1.log.gz)

**Comment by LXGaming** [comment]
Simply remove MixinBootstrap, There are other mods which are adding the Mixin library so MixinBootstrap is not required.

**Comment by LXGaming** [comment]
~~Was MixinBootstrap added manually or is it being downloaded with the pack?~~

Tested importing the pack with MultiMC and MixinBootstrap was not included.

**Comment by pirateninjaboi** [comment]
well, when i remove mixinbootstrap, the game makes it to the loading mods menu part, but the moment it finishes, dynamic surroundings(the mod that requires mixinbootstrap) causes the game to crash right before making it to the loading screen

**Comment by LXGaming** [comment]
Can you upload the new crash report

**Comment by pirateninjaboi** [comment]
you mean the one when it crashes at the menu due to dynamic surroundings?

**Comment by LXGaming** [comment]
Yes

**Comment by pirateninjaboi** [comment]
alright, ill need a bit though,takes a while to load all the mods in

**Comment by pirateninjaboi** [comment]
so as it turns out, the first log i sent you wasnt the one i meant to, so heres both of them, the one without mixin is the second one

[crashwithmixin.txt](https://github.com/LXGaming/MixinBootstrap/files/5863962/crashwithmixin.txt)
[crashwithoutmixin.txt](https://github.com/LXGaming/MixinBootstrap/files/5863963/crashwithoutmixin.txt)

**Comment by LXGaming** [comment]
Could you please upload your debug.log so we can figure out why the Mixin from DS isn't applying.

I've launched All the Mods 3 - ATM3-v6.0.0 with no issues on MultiMC

**Comment by pirateninjaboi** [comment]
how do i find the debug log?

**Comment by LXGaming** [comment]
Instance Folder/logs/debug.log

**Comment by pirateninjaboi** [comment]
theres no debug log, just an encoded log, and latest.log, but latest log isnt encoded, so do you want that?

**Comment by LXGaming** [comment]
Yeah sure upload the latest.log

**Comment by pirateninjaboi** [comment]
[latest.log](https://github.com/LXGaming/MixinBootstrap/files/5864021/latest.log)

**Comment by LXGaming** [comment]
Ok, I was confused as I couldn't find Dynamic Surroundings in the ATM 3 pack, I going to assume that you've added it to the pack.

Download MixinBootstrap and rename the jar so its says "aaaaaMixinBootstrap-1.0.5.jar", This will ensure Mixin 0.8 get loaded first which should fix the issue

**Comment by LXGaming** [comment]
https://github.com/LXGaming/MixinBootstrap/releases/tag/v1.0.6

This version should work

**Comment by pirateninjaboi** [comment]
im loading in, as i stated it takes a while, so ill get back to you when its done.

**Comment by pirateninjaboi** [comment]
alright, so i renamed it to what you said, im using the 1.0.5 still, and it worked! thanks!

**Comment by LXGaming** [comment]
Awesome
