### ISSUE TITLE
Keep getting this error with mixin. I host a minecraft server, so this is in the pack for that. Id appreciate any help, this is above me 

### ISSUE THREAD

**Issue by That-One-Bagel** [LXGaming/MixinBootstrap#42]
16:03:56.331
[java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)
16:03:56.331
[java.lang.ThreadGroup:uncaughtException:1061]: Caused by: java.lang.ClassNotFoundException: net.minecraft.util.math.Vec3i
16:03:56.331
[java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.ClassLoader.findClass(ClassLoader.java:530)
16:03:56.331
[java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
16:03:56.332
[java.lang.ThreadGroup:uncaughtException:1061]: 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:104)
16:03:56.332
[java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
16:03:56.332
[java.lang.ThreadGroup:uncaughtException:1061]: 	... 14 more
16:03:56.333
[java.lang.Throwable:printStackTrace:643]: 	Suppressed: java.lang.ClassNotFoundException
16:03:56.333
[java.lang.Throwable:printStackTrace:643]: 		at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:263)
16:03:56.333
[java.lang.Throwable:printStackTrace:643]: 		at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:134)
16:03:56.333
[java.lang.Throwable:printStackTrace:643]: 		at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:96)
16:03:56.334
[java.lang.Throwable:printStackTrace:643]: 		... 15 more
16:03:56.975

Java HotSpot(TM) 64-Bit Server VM warning: ignoring option PermSize=256m; support was removed in 8.0
16:03:56.975
Process crashed with exit code 1

**Comment by LXGaming** [comment]
Can you please upload the `debug.log` file

**Comment by LXGaming** [comment]
Closing due to no response.

If you still require help with this issue please reply here instead of open a new issue.
