### ISSUE TITLE
Crash on startup because of JEID

### ISSUE THREAD

**Issue by Cixiid** [LXGaming/MixinBootstrap#43]
**Environment**
- MixinBootstrap version: 1.0.6
- Forge version: 14.23.5.2854
- Minecraft version: 1.12.2
- Java version: 1.8.0_51
- Mods: JustEnoughId's (seem to be the problem) 

**Issue Description**
Hello, when i launch my game i got an IllegalAccessError with mixin, when i try to use MixinBootstrap, i still got the issues..

Thanks in advance

[crash-2021-03-04_00.01.07-client.txt](https://github.com/LXGaming/MixinBootstrap/files/6079719/crash-2021-03-04_00.01.07-client.txt)

[latest.log](https://github.com/LXGaming/MixinBootstrap/files/6079728/latest.log)

**Comment by LXGaming** [comment]
Try updating [VanillaFix](https://www.curseforge.com/minecraft/mc-mods/vanillafix/files/2915154)

**Comment by Cixiid** [comment]
Hello, thanks for the fast answer, I have already the latest update of Vanilla Fix..

**Comment by LXGaming** [comment]
The crash report you posted shows `VanillaFix-1.0.10-99` the latest on CurseForge is `VanillaFix 1.0.10-150`

**Comment by Cixiid** [comment]
Oh... Gonna check my folder and tell you then.. sorry for being dumb lol I get back to you in like 5 minutes (time for my PC to launch)

**Comment by Cixiid** [comment]
My guy you save my day thanks you very much, and stay safe <3

**Comment by LXGaming** [comment]
No Problem
