### ISSUE TITLE
Dont Work on Server

### ISSUE THREAD

**Issue by LPDMinecraft** [LXGaming/MixinBootstrap#44]
**Environment**
- MixinBootstrap version: 1.0.6
- Forge version: Client: "35.1.36" Server: "35.3.17"
- Minecraft version: 1.16.4
- Java version: 1.8 and 1.11 and 1.12
- Mods: 
![grafik](https://user-images.githubusercontent.com/65708374/111754956-dd0dae80-8898-11eb-836f-c93bdd722759.png)

**Issue Description**

It dont work on my server

[latest.log](https://github.com/LXGaming/MixinBootstrap/files/6169810/latest.log)
[debug.log](https://github.com/LXGaming/MixinBootstrap/files/6169811/debug.log)

**Comment by LXGaming** [comment]
What's the issue?

With the Forge version you are running you don't need MixinBootstrap as the Mixin library is provided by Forge.

**Comment by LPDMinecraft** [comment]
? I cant get on my server, because the tag size is too big. And this I need for another Mod.

**Comment by LXGaming** [comment]
Can you provide your client logs.

**Comment by LPDMinecraft** [comment]
![grafik](https://user-images.githubusercontent.com/65708374/111783475-8ca74880-88ba-11eb-935c-c03e9786f13b.png)

**Comment by LXGaming** [comment]
Yeah I'm not sure, Something on your server is sending too much NBT Data, The XL Packets mod isn't going to work as it doesn't change the NBT size limits which is causing your error.

I cannot do anything regarding this issue as it has nothing to do with MixinBootstrap, this is hardcoded limit in Minecraft.
