### ISSUE TITLE
Crashes on startup, no crash report

### ISSUE THREAD

**Issue by TopOnPC** [LXGaming/MixinBootstrap#45]
**Environment**
- MixinBootstrap version: 1.0.2
- Forge version: 1.15.2-forge-31.2.50
- Minecraft version: 1.15.2
- Java version: Java 8 Update 291
- Mods: none (to test the mod)

**Issue Description**

I'm trying to install Phosphor and Lithium, which requires MixinBootstrap for 1.15.2, but when I put the mod into the mods folder and start up minecraft it instantly crashes with exit code 0. I've tried with no other mods installed yet it still crashes, any idea why? Thanks!

[debug.log](https://github.com/LXGaming/MixinBootstrap/files/6354687/debug.log)
[latest.log](https://github.com/LXGaming/MixinBootstrap/files/6354688/latest.log)

**Comment by LXGaming** [comment]
This issue was fixed in [v1.0.3](https://github.com/LXGaming/MixinBootstrap/releases/tag/v1.0.3), However you can simply remove MixinBootstrap as the Mixin library is included by Forge.

**Comment by TopOnPC** [comment]
Thanks! So I tried it with no other mods, and it does work, but when I put the mods in, it crashes when starting a singleplayer world. Any idea why? Thanks!
[latest.log](https://github.com/LXGaming/MixinBootstrap/files/6355038/latest.log)
[crash-2021-04-22_03.19.27-server.txt](https://github.com/LXGaming/MixinBootstrap/files/6355034/crash-2021-04-22_03.19.27-server.txt)
[debug.log](https://github.com/LXGaming/MixinBootstrap/files/6355036/debug.log)

**Comment by LXGaming** [comment]
Looks like a compatibility issue with [Lithium](https://www.curseforge.com/minecraft/mc-mods/lithium-forge) and [Performant](https://www.curseforge.com/minecraft/mc-mods/performant)

Remove Lithium as it's no longer being updated.

**Comment by TopOnPC** [comment]
Yep, that fixed it, thank you so much!
