### ISSUE TITLE
Mod isn't shown in the modlist

### ISSUE THREAD

**Issue by ghost** [LXGaming/MixinBootstrap#46]
**Environment**
- MixinBootstrap version: newest
- Forge version: 1.16.5 Forge

**Issue Description**
I'm playing on a mac and the MixinBootstrap is in my modsfolder, but in minecraft in the modlist it is not shown to me.

**Comment by ghost** [comment]
Modfolder:
Create - curseforge.com/minecraft/mc-mods/create

JEI (Just enough Items) - curseforge.com/minecraft/mc-mods/jei

Scarecrow Spawn Chunk Loader - curseforge.com/minecraft/mc-mods/scarecrow-spawn-chunk-loader

ChunkLoaders - curseforge.com/minecraft/mc-mods/chunk-loaders
SuperMartijn642's Config Lib - curseforge.com/minecraft/mc-mods/supermartijn642s-config-lib

Global XP - curseforge.com/minecraft/mc-mods/global-xp

Traveler's Backpack - curseforge.com/minecraft/mc-mods/travelers-backpack

The One Probe - curseforge.com/minecraft/mc-mods/the-one-probe

Optifine - optifine.net

Xaero's World Map - curseforge.com/minecraft/mc-mods/xaeros-world-map

More Overlays updated - curseforge.com/minecraft/mc-mods/more-overlays-updated

Shulker Tooltip - curseforge.com/minecraft/mc-mods/shulker-tooltip

Useful Railroads - curseforge.com/minecraft/mc-mods/useful-railroads
U Team Core - curseforge.com/minecraft/mc-mods/u-team-core

XL Packets - curseforge.com/minecraft/mc-mods/xl-packets
MixinBootstrap - curseforge.com/minecraft/mc-mods/mixinbootstrap

**Comment by LXGaming** [comment]
This is intentional as MixinBootstrap is more of a plugin for [modlauncher](https://github.com/cpw/modlauncher) than a mod for [MinecraftForge](https://github.com/MinecraftForge/MinecraftForge) so it will not show up in the Forge mod list.

You can remove MixinBootstrap as the Mixin library is included by Forge.

**Comment by ghost** [comment]
Ok thanks
