### ISSUE TITLE
Latest version incompatible with JustEnoughIDs (1.12.2)

### ISSUE THREAD

**Issue by BjornTjockPals** [LXGaming/MixinBootstrap#48]
File of version 1.1.0 (1.12.2) begins with a `_` which causes crash on startup. Simply renaming it fixes this issue.

**Comment by LXGaming** [comment]
Can you provide the `debug.log` for the crash, The purpose of the underscore is to ensure MixinBootstrap is loaded first.

**Comment by BjornTjockPals** [comment]
Sorry my internet is shit, here it is. It's probably because other mods i have but im not good in interpretating logs.
[debug.zip](https://github.com/LXGaming/MixinBootstrap/files/7039238/debug.zip)

**Comment by LXGaming** [comment]
Thank you very much for the `debug.log`.

It appears to be an issue with [JustEnoughIDs](https://www.curseforge.com/minecraft/mc-mods/jeid) not supporting Mixin 0.8.3, The simplest solution is to just remove MixinBootstrap as JustEnoughIDs includes the Mixin library it and other mods should work fine without MixinBootstrap.

Technical Information:
JustEnoughIDs cannot access `org.spongepowered.asm.mixin.transformer.MixinProcessor` in Mixin 0.8.3 as the class was made package-private.
https://github.com/DimensionalDevelopment/JustEnoughIDs/blob/eeaae8c0ee9305e5bf876c949a5e00374ef90807/src/main/java/org/dimdev/jeid/mixin/init/MixinLoader.java#L60-L66

**Comment by Mysticpasta1** [comment]
I'm the new maintainer of JEID, if someone can help me fix the issue I will get it released asap
