### ISSUE TITLE
ReEntrantTransformerError: Re-entrance error after installing with FancyMenu [FORGE]

### ISSUE THREAD

**Issue by Falcion** [LXGaming/MixinBootstrap#49]
#### Environment

**MixinBootstrap:** 1.1.0;
**Forge version:** 14.23.5.2855;
**Minecraft version:** 1.12.2;
**Java version:** jre1.8.0_301;

<details>
  <summary>List of mods: 186. </summary>

<li>/dank/null</li>
<li>AI Improvements</li>
<li>Actually Additions</li>
<li>Actually Computers</li>
<li>Actually Recycling</li>
<li>Additional Banners</li>
<li>AppleCore</li>
<li>AppleSkin</li>
<li>AttributeFix</li>
<li>AutoRegLib</li>
<li>B.A.S.E</li>
<li>Bad Wither No Cookie - Reloaded</li>
<li>BdLib</li>
<li>Bed Patch</li>
<li>Better Burning</li>
<li>Better Ping Display</li>
<li>Better Placement</li>
<li>Better than Mending</li>
<li>BetterFPS</li>
<li>Biomes O' Plenty</li>
<li>Bookshelf</li>
<li>Brandon's Core</li>
<li>COFH Core </li>
<li>COFH World</li>
<li>Carry On</li>
<li>Ceramics</li>
<li>Chameleon</li>
<li>Chisel</li>
<li>Chunk-Pregenerator</li>
<li>Clumps</li>
<li>CodeChicken Lib 1.8.+</li>
<li>Comforts (Forge)</li>
<li>Common Capabilities</li>
<li>Configurable Cane</li>
<li>ConnectedTexturesMod</li>
<li>Construct's Armory</li>
<li>ContainerFix</li>
<li>ContentTweaker</li>
<li>Controlling</li>
<li>CraftTweaker</li>
<li>Crafting Tweaks</li>
<li>Cucumber Library</li>
<li>CustomSkinLoader</li>
<li>Cyclops Core</li>
<li>Default Options</li>
<li>Dimension Stages</li>
<li>Draconic Evolution</li>
<li>Dynamic Surroundings</li>
<li>Ender Core</li>
<li>Ender IO</li>
<li>Ender Tweaker</li>
<li>Erdbeerbaer's GUI Library</li>
<li>Expanded Equivalence</li>
<li>Extended Crafting</li>
<li>Extra Utilities</li>
<li>Extreme Reactors</li>
<li>FPS Reducer</li>
<li>FTB Backups</li>
<li>FTB Library (Forge) (Legacy)</li>
<li>FTB Money </li>
<li>FTB Quests</li>
<li>Factory Tech</li>
<li>FancyMenu [Forge]</li>
<li>Fast Furnace</li>
<li>Fast Leaf Decay</li>
<li>Fast Workbench</li>
<li>FoamFix</li>
<li>Forestry</li>
<li>Future MC</li>
<li>Game Stages</li>
<li>Gendustry</li>
<li>Guide-API</li>
<li>GunpowderLib</li>
<li>Hammer (Lib) Core</li>
<li>Illagers+</li>
<li>Immersive Cables</li>
<li>Immersive Engineering</li>
<li>Immersive Petroleum</li>
<li>Immersive Tech</li>
<li>Industrial Foregoing</li>
<li>Integrated Dynamics</li>
<li>Integrated Tunnels</li>
<li>Integration Foregoing</li>
<li>Inventory Tweaks</li>
<li>Iron Backpacks</li>
<li>Iron Chest</li>
<li>It's the little things</li>
<li>Item Blacklist</li>
<li>Item Filters (Forge)</li>
<li>Item Stages</li>
<li>JEI</li>
<li>JEI Bees</li>
<li>JEI Villagers</li>
<li>JEIDs</li>
<li>JER</li>
<li>JourneyMap</li>
<li>LibraryEx</li>
<li>MTLib</li>
<li>Magneticraft</li>
<li>Mantle</li>
<li>McJtyLib</li>
<li>Mekanism</li>
<li>Mekanism Generators</li>
<li>Mekanism Tools</li>
<li>Mod Name Tooltip</li>
<li>Mod Tweaker</li>
<li>ModelLoader</li>
<li>Modpack Configuration Checker</li>
<li>Morpheus</li>
<li>Mouse Tweaks</li>
<li>Nature's Compass</li>
<li>Nether Portal Fix</li>
<li>NetherEx</li>
<li>No Mobs Spawning on Trees</li>
<li>NuclearCraft</li>
<li>OpenBlocks</li>
<li>OpenComputers</li>
<li>OpenModsLib</li>
<li>Ore Excavation</li>
<li>Ore Excavation Integration</li>
<li>OreLib</li>
<li>Phosphor</li>
<li>Placebo</li>
<li>PlusTiC</li>
<li>PneumaticCraft: Repressurized</li>
<li>ProjectE</li>
<li>Quark</li>
<li>RFTools</li>
<li>RFTools Control</li>
<li>RFTools Dimension</li>
<li>Railcraft</li>
<li>RandomPatches</li>
<li>RandomTweaks</li>
<li>Reborn Core</li>
<li>Reborn Storage</li>
<li>Recipe Stages</li>
<li>Redstone Flux</li>
<li>Refined Storage</li>
<li>Refined Storage Addons</li>
<li>Resource Loader</li>
<li>Resource Reloader</li>
<li>Shadowfacts' Forgelin</li>
<li>Silent Gear</li>
<li>Silent Gems</li>
<li>Silent Gems - TiC Support</li>
<li>Silent Gems: Extra Parts</li>
<li>Silent Lib</li>
<li>Smooth Font</li>
<li>Storage Drawers</li>
<li>Surge</li>
<li>TOP Addons</li>
<li>Tech Reborn</li>
<li>Tesla Core Lib</li>
<li>TexFix</li>
<li>The One Probe</li>
<li>The Spice of Life</li>
<li>Thermal Cultivation</li>
<li>Thermal Dynamics</li>
<li>Thermal Expansion</li>
<li>Thermal Foundation</li>
<li>Thermal Innovation</li>
<li>Thermal Tinkering</li>
<li>Tinker I/O</li>
<li>Tinker's Stages</li>
<li>Tinkers Complement</li>
<li>Tinkers Construct</li>
<li>Tinkers JEI</li>
<li>Tinkers Tool Leveling</li>
<li>Toast Control</li>
<li>VanillaFix</li>
<li>VanillaTweaks</li>
<li>Villager Names</li>
<li>WorldEdit</li>
<li>WorldEditCUI Forge Edition 3</li>
<li>XNet</li>
<li>YUNG's Better Caves (Forge)</li>
<li>YUNG's Better Mineshafts (Forge)</li>
<li>ZenStages</li>
<li>ZeroCore</li>
<li>p455w0rd's Library</li>
</details>

**Issue Description**
Minecraft application does not open, not even a millisecond of the working window: but the process of JVM and Minecraft Launcher is active.

[latest.log](https://hastebin.com/zudesirono.yaml)
[debug.log](https://hastebin.com/mutaxuqeno.sql)

**Comment by LXGaming** [comment]
I was able to reproduce the issue with just FancyMenu and RandomPatches, The root cause of the crash appears to be due to `[randompatches]: Failed to transform class: net.minecraft.client.Minecraft`, This is most likely a conflict between FancyMenu and RandomPatches.

Please try setting `patchMinecraftClass` to `false` in the `randompatches.cfg`

**Comment by Falcion** [comment]
Tried changing `patchMinecraftClass` to `false` in the `randompatches.cfg`.
Still error, but different, now Minecraft appears and crashes immediately with new error: ```java.lang.IllegalAccessError: tried to access class org.spongepowered.asm.mixin.transformer.MixinProcessor from class net.minecraftforge.fml.common.Loader``` 

[latest.log](https://hastebin.com/ukudotaxub.rb)
[debug.log](https://dropmefiles.com/wkMMK "File was too big for any bin-website").

**Comment by LXGaming** [comment]
https://github.com/LXGaming/MixinBootstrap/issues/48#issuecomment-904653743
