### ISSUE TITLE
Please Update CurseForge Page to Reflect Versions Supported

### ISSUE THREAD

**Issue by ByThePowerOfScience** [LXGaming/MixinBootstrap#55]
This isn't a bug report, but it's the only way I know how to ping you about this.  Sorry.

The CurseForge page is really vague about what versions it supports.  Could you please update the 1.1.0 file to show that it supports all versions that it supports (since it currently doesn't say it supports 1.12.2), or explicitly state in the description of the project that Minecraft version doesn't matter?  Also, could you please add the suggested method of including the mod in your build.gradle? (For example, do you need to have Mixin as one of your build dependencies if this mod is installed?)

Thank you, and sorry for the GitHub ping!

**Comment by LXGaming** [comment]
I see what you mean about CurseForge being vague, I've added the versions to the file description.

You don't include the mod in the `build.gradle` you simply add the Mixin dependency `org.spongepowered:mixin:0.8.x`, I personally prefer to ship multiple jars one with the Mixin dependency and one without, this makes it easier to resolve Mixin version conflicts. If your mod is going to require MixinBootstrap then you don't need to include the Mixin dependency.

**Comment by LXGaming** [comment]
Readme updated: https://github.com/LXGaming/MixinBootstrap#development
