### ISSUE TITLE
Modrinth?

### ISSUE THREAD

**Issue by Keksuccino** [LXGaming/MixinBootstrap#56]
Hi!

Can you upload MixinBootstrap to Modrinth, please? Would like to use it as dependency for the 1.12 versions of FancyMenu and Konkrete, just like I do on CurseForge :)

Thank you for your time and have a great day!

**Comment by LXGaming** [comment]
Hey,

This is an awesome idea, I'll have to look into uploading my other mods to Modrinth as well. I've created a MixinBootstrap project on Modrinth and it's currently pending review.

https://modrinth.com/user/LXGaming
https://modrinth.com/mod/mixinbootstrap

**Comment by Keksuccino** [comment]
That's great to hear, thank you! :D

**Comment by LXGaming** [comment]
Closing this issue as the MixinBootstrap project on Modrinth has been approved.
