### ISSUE TITLE
Mixin Extras maybe?

### ISSUE THREAD

**Issue by viciscat** [LXGaming/MixinBootstrap#57]
Heya! I think it would be interesting to add [Mixin Extras](https://github.com/LXGaming/MixinBootstrap) to the bootstrap! Cuz it makes life a heck of a lot easier to work with mixins and making them compatible with other mods (Wrap annotations).

**Comment by LXGaming** [comment]
Unfortunately I believe this is out of scope for this project, MixinBootstrap was designed to simply inject Mixin into Forge nothing more. there are plenty of other projects out there that can replace MixinBootstrap and have added features which can help mod developers.
