### ISSUE TITLE
Compatibility issue with Serene Seasons

### ISSUE THREAD

**Issue by Purplo262** [LXGaming/MixinBootstrap#6]
Mixinbootstrap appears to have a compatibility issue with the Serene Seasons mod.

Whilst using the two together (in this case I was using Mixinbootstrap for the immersive portals and the snow!realmagic! mod) an issue arises where whenever someone sleeps, it causes the season to change entirely. (like going from spring to fall) 

Removing Mixinbootstrap seems to have fixed the issue, but I would love for it to compatible so I can use these three wonderful mods together!

**Comment by LXGaming** [comment]
Is this issue occurring on single player or multiplayer?
Can you provide a list of the mods and the versions you are running.

**Comment by LXGaming** [comment]
Serene Seasons v1.15.2-3.0.0.67 fixes the issue of the seasons wildly changing while being in a bed.

For some reason when SnowRealMagic is present it is preventing the seasons from changing.

**Comment by Purplo262** [comment]
Yep! I tried using the latest versions of Mixinbootstrap, immersive portals (for forge) and serene seasons and they work fine. Haven't tried it with Snow!Realmagic! yet though.

**Comment by LXGaming** [comment]
Closing as this is an issue with Serene Seasons, Follow the mentioned issue above for updates.
