### ISSUE TITLE
MixinBootstrap causes block model tessellating problems with Tetra mod

### ISSUE THREAD

**Issue by ZaRx485** [LXGaming/MixinBootstrap#9]
I was playing a modded Minecraft save when game crashed. The crash report said that it was because of a tessellating block model for Tetra, so I went to the Tetra issue tracker where someone else had the same problem as me. One of the commenters had created a fresh save with only Tetra, and gone through the entire op's mod list until he found the problem, which was MixinBootstrap.

Pastebin link for crash report: https://pastebin.com/3nMjKvNu

Same issue on Tetra issue tracker: https://github.com/mickelus/tetra/issues/130

Minecraft Version: 1.14.4
Forge Version: 28.2.0

**Comment by LXGaming** [comment]
Blame [BetterFoliage](https://github.com/octarine-noise/BetterFoliage), They are passing null in place of ModelData to the BlockRendererDispatcher [here](https://github.com/octarine-noise/BetterFoliage/blob/aa91aed58e3b1fe117c7332c3fa587879e231761/src/main/kotlin/mods/octarinecore/client/render/BlockContext.kt#L69), A null value isn't allowed, IntelliJ even tells you that passing null is a stupid idea.
![RenderCtx](https://user-images.githubusercontent.com/10443061/77863494-6cccde00-727f-11ea-8abd-0b1bb5b91c77.PNG)

Further more they redirect `ChunkRender::renderBlock` to a hook [here](https://github.com/octarine-noise/BetterFoliage/blob/aa91aed58e3b1fe117c7332c3fa587879e231761/src/main/kotlin/mods/betterfoliage/client/Hooks.kt#L69), This hook has a parameter for ModelData but they don't pass it along. They are essentially fucking up the entire rendering pipeline.

**Comment by ZaRx485** [comment]
Ah okay thank you. I guess it would have been better if I'd done some testing on my part, but now that I know it wasn't Bootstrap I'll probably try and test this myself and see if BetterFoliage knows anything about why this is happening.

**Comment by sirati** [comment]
as mickelus/tetra#130 is closed, this should be closed too
